preload:
  - ApplicationController

controllers:
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth
    controller: AuthLoginController


  - path: /dashboard
    controller: DashboardController
  - path: /static
    controller: StaticController
  - path: /
    controller: IndexController
