preload:
  - ApplicationController
  - SystemController

controllers:
  - path: /auth/signup
    controller: AuthSignupController
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth
    controller: AuthLoginController

  - path: /system/config
    controller: SystemConfigurationController
  - path: /system
    controller: SystemDashboardController

  - path: /dashboard
    controller: DashboardController
  - path: /static
    controller: StaticController
  - path: /
    controller: IndexController
