preload:
  - ApplicationController
  - ApiController
  - CaseController
  - SystemController

controllers:
  - path: /auth/reset
    controller: AuthResetController
  - path: /auth/signup
    controller: AuthSignupController
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth/mfa/totp
    controller: AuthMfaTotpController
  - path: /auth/sso/magenta
    controller: AuthSsoMagentaController
  - path: /auth/sso
    controller: AuthSsoController
  - path: /auth
    controller: AuthLoginController

  - path: /user/mfa/recovery
    controller: UserSettingsMfaRecoveryController
  - path: /user/mfa/totp
    controller: UserSettingsMfaTotpController
  - path: /user/mfa
    controller: UserSettingsMfaController
  - path: /user
    controller: UserSettingsController

  - path: /case/:case_id/correspondence/send
    controller: CaseCorrespondenceSendController
  - path: /case/:case_id/correspondence/:cc_id/dl
    controller: CaseCorrespondenceDownloadController
  - path: /case/:case_id/correspondence/:cc_id
    controller: CaseCorrespondenceEditController
  - path: /case/:case_id/task/add
    controller: CaseTaskAddController
  - path: /case/:case_id/task/:task_id
    controller: CaseTaskEditController
  - path: /case/:case_id/spend/add
    controller: CaseSpendAddController
  - path: /case/:case_id/spend/:spend_id/receipt
    controller: CaseSpendReceiptController
  - path: /case/:case_id/spend/:spend_id/approve
    controller: CaseSpendApproveController
  - path: /case/:case_id/spend/:spend_id
    controller: CaseSpendEditController
  - path: /case/:case_id/note/add
    controller: CaseNoteAddController
  - path: /case/:case_id/note/:note_id/history
    controller: CaseNoteHistoryController
  - path: /case/:case_id/note/:note_id
    controller: CaseNoteEditController
  - path: /case/:case_id/edit/rc
    controller: CaseEditReconnectController
  - path: /case/:case_id/edit
    controller: CaseEditController
  - path: /case/:case_id/view
    controller: CaseViewController
  - path: /case/create
    controller: CaseCreateController
  - path: /case/list-tasks
    controller: CaseListTasksController
  - path: /case/list
    controller: CaseListController
  - path: /case/search
    controller: CaseSearchController
  - path: /case
    controller: CaseIndexController

  - path: /prison-assignees
    controller: PrisonAssigneesController

  - path: /system/debug
    controller: SystemDebugController
  - path: /system/mailtemplates
    controller: SystemMailTemplatesController
  - path: /system/prison
    controller: SystemPrisonController
  - path: /system/worker
    controller: SystemWorkerController
  - path: /system/apikey
    controller: SystemApiKeyController
  - path: /system/roles/groups
    controller: SystemRoleGroupsController
  - path: /system/roles
    controller: SystemRolesController
  - path: /system/config
    controller: SystemConfigurationController
  - path: /system
    controller: SystemDashboardController

  - path: /o/request
    controller: OutsideRequestController

  - path: /dashboard
    controller: DashboardController
  - path: /
    controller: IndexController

  - path: /-/language
    controller: DashLanguageController
  - path: /-/debug
    controller: DashDebugController
    only:
      env:
        - development
        - test
  
  - path: /filedl
    controller: FileDownloadController

  - path: /static
    controller: StaticController

  - path: /api/meta
    controller: ApiMetaController
  - path: /api/request
    controller: ApiRequestController
