preload:
  - ApplicationController
  - SystemController

controllers:
  - path: /auth/signup
    controller: AuthSignupController
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth
    controller: AuthLoginController

  - path: /user
    controller: UserSettingsController

  - path: /system/config
    controller: SystemConfigurationController
  - path: /system
    controller: SystemDashboardController

  - path: /dashboard
    controller: DashboardController

  - path: /-/language
    controller: DashLanguageController
  - path: /-/debug
    controller: DashDebugController
    only:
      env:
        - development
        - test

  - path: /static
    controller: StaticController
  - path: /
    controller: IndexController
