preload:
  - ApplicationController
  - CaseController
  - SystemController

controllers:
  - path: /auth/signup
    controller: AuthSignupController
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth/mfa/totp
    controller: AuthMfaTotpController
  - path: /auth
    controller: AuthLoginController

  - path: /user/mfa/recovery
    controller: UserSettingsMfaRecoveryController
  - path: /user/mfa/totp
    controller: UserSettingsMfaTotpController
  - path: /user/mfa
    controller: UserSettingsMfaController
  - path: /user
    controller: UserSettingsController

  - path: /case
    controller: CaseIndexController

  - path: /system/roles
    controller: SystemRolesController
  - path: /system/config
    controller: SystemConfigurationController
  - path: /system
    controller: SystemDashboardController

  - path: /dashboard
    controller: DashboardController

  - path: /-/language
    controller: DashLanguageController
  - path: /-/debug
    controller: DashDebugController
    only:
      env:
        - development
        - test

  - path: /static
    controller: StaticController
  - path: /
    controller: IndexController
