preload:
  - ApplicationController
  - CaseController
  - SystemController

controllers:
  - path: /auth/signup
    controller: AuthSignupController
  - path: /auth/logout
    controller: AuthLogoutController
  - path: /auth/mfa/totp
    controller: AuthMfaTotpController
  - path: /auth
    controller: AuthLoginController

  - path: /user/mfa/recovery
    controller: UserSettingsMfaRecoveryController
  - path: /user/mfa/totp
    controller: UserSettingsMfaTotpController
  - path: /user/mfa
    controller: UserSettingsMfaController
  - path: /user
    controller: UserSettingsController

  - path: /case/:case_id/task/add
    controller: CaseTaskAddController
  - path: /case/:case_id/task/:task_id
    controller: CaseTaskEditController
  - path: /case/:case_id/spend/add
    controller: CaseSpendAddController
  - path: /case/:case_id/spend/:spend_id/approve
    controller: CaseSpendApproveController
  - path: /case/:case_id/spend/:spend_id
    controller: CaseSpendEditController
  - path: /case/:case_id/note/add
    controller: CaseNoteAddController
  - path: /case/:case_id/note/:note_id
    controller: CaseNoteEditController
  - path: /case/:case_id/view
    controller: CaseViewController
  - path: /case/create
    controller: CaseCreateController
  - path: /case
    controller: CaseIndexController

  - path: /system/worker
    controller: SystemWorkerController
  - path: /system/roles
    controller: SystemRolesController
  - path: /system/config
    controller: SystemConfigurationController
  - path: /system
    controller: SystemDashboardController

  - path: /dashboard
    controller: DashboardController

  - path: /-/language
    controller: DashLanguageController
  - path: /-/debug
    controller: DashDebugController
    only:
      env:
        - development
        - test

  - path: /static
    controller: StaticController
  - path: /
    controller: IndexController
