:schedule:
  email_queue_send:
    cron: '* * * * *'
    class: "Kukupa::Workers::EmailQueueSendWorker"

  task_reminder:
    cron: '0 0 * * *'
    class: "Kukupa::Workers::CaseTaskReminderWorker"

  timeline_reminder:
    cron: '0 0 * * *'
    class: "Kukupa::Workers::CaseTimelineReminderWorker"

  sync_incoming_email:
    cron: '*/5 * * * *'
    class: "Kukupa::Workers::SyncIncomingEmailWorker"

  sync_prisons:
    cron: '*/30 * * * *'
    class: "Kukupa::Workers::SyncPrisonsWorker"

  sync_cases:
    cron: '*/10 * * * *'
    class: "Kukupa::Workers::SyncCasesWorker"

  sync_new_cases:
    cron: '*/30 * * * *'
    class: "Kukupa::Workers::SyncNewReconnectCasesWorker"

  create_penpals:
    cron: '*/30 * * * *'
    class: "Kukupa::Workers::CreateReconnectPenpalsWorker"
