:schedule:
  email_queue_send:
    cron: '* * * * *'
    class: "Kukupa::Workers::EmailQueueSendWorker"

  task_reminder:
    cron: '0 0 * * *'
    class: "Kukupa::Workers::CaseTaskReminderWorker"

  sync_cases:
    cron: '*/10 * * * *'
    class: "Kukupa::Workers::SyncCasesWorker"
